version: '3'
services:
  api:
    image: "api-gauchadas"
    build: .
    depends_on:
       - db
    env_file:
      - .env
    ports:
      - "8080:8080"
  db:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongo-data:/data/db
      - ./volumes/mongo-config:/data/configdb
